### ISSUE TITLE
[Dev build 34] Last page of shop fails to populate

### ISSUE THREAD

**Issue by mb243** [remremrem/HyperMerchant#10]
The last page of the shop fails to populate correctly if it's less than a full page. No icons display, but clicking on spaces in the inventory does cause items to be bought and sold, and the icon appears after. 

Here's the java error:

```
31.01 16:45:14 [Server] ERROR Could not pass event InventoryClickEvent to HyperMerchant v1.6.1-dev
31.01 16:45:14 [Server] INFO org.bukkit.event.EventException
31.01 16:45:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1839) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
31.01 16:45:14 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
31.01 16:45:14 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
31.01 16:45:14 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B
31.01 16:45:14 [Server] INFO at grokswell.hypermerchant.ShopMenu.loadPage(ShopMenu.java:250) ~[?:?]
31.01 16:45:14 [Server] INFO at grokswell.hypermerchant.ShopMenu.nextPage(ShopMenu.java:262) ~[?:?]
31.01 16:45:14 [Server] INFO at grokswell.hypermerchant.ShopMenu.handleMenuCommand(ShopMenu.java:461) ~[?:?]
31.01 16:45:14 [Server] INFO at grokswell.hypermerchant.ShopMenu.onInventoryClickOrCreative(ShopMenu.java:567) ~[?:?]
31.01 16:45:14 [Server] INFO at grokswell.hypermerchant.ShopMenu.onInventoryClick(ShopMenu.java:548) ~[?:?]
31.01 16:45:14 [Server] INFO at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source) ~[?:?]
31.01 16:45:14 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
31.01 16:45:14 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
31.01 16:45:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-4741400-c1aa859]
31.01 16:45:14 [Server] INFO ... 15 more
```

**Comment by remremrem** [comment]
This issue is now resolved. Please try Dev build 36 http://ci.citizensnpcs.co/job/HyperMerchant/36/

**Comment by mb243** [comment]
Perfect, thanks! 👍
