### ISSUE TITLE
Can't execute /shopmenu and /remotemenu command

### ISSUE THREAD

**Issue by tostasifone** [remremrem/HyperMerchant#11]
Hello, Can't execute /shopmenu, /remotemenu command and rightclick on npc don't work.

This happen after i ban all item from the shop and allow just 5 item.
 
org.bukkit.command.CommandException: Unhandled exception executing command 'remotemenu' in plugin HyperMerchant v1.59
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1353) [spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188) [spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
 at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B
 at grokswell.hypermerchant.ShopMenu.loadPage(ShopMenu.java:245) ~[?:?]
 at grokswell.hypermerchant.ShopMenu.<init>(ShopMenu.java:115) ~[?:?]
 at grokswell.hypermerchant.HyperMerchantPlugin.onCommand(HyperMerchantPlugin.java:99) ~[?:?]
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.11.2.jar:git-Spigot-625bc00-d09304e]
 ... 15 more

Can you help me?

**Comment by remremrem** [comment]
I will look into this tonight. Can you tell me what 5 items you left unbanned?

**Comment by tostasifone** [comment]
I have closed this issue because now it work. Think thant my server failed to autoupdate the plugin. 
The 5 item are: wood sword + leather armor set
