### ISSUE TITLE
Error while enabling HyperMerchant on Spigot 1.12-pre2

### ISSUE THREAD

**Issue by mb243** [remremrem/HyperMerchant#13]
```
[18:02:56] [Server thread/INFO]: [HyperMerchant] Enabling HyperMerchant v1.6.1-dev
[18:02:56] [Server thread/ERROR]: Error occurred while enabling HyperMerchant v1.6.1-dev (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
        at grokswell.util.Settings.loadConfig(Settings.java:83) ~[?:?]
        at grokswell.util.Settings.<init>(Settings.java:67) ~[?:?]
        at grokswell.hypermerchant.HyperMerchantPlugin.onEnable(HyperMerchantPlugin.java:364) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by remremrem** [comment]
Thank you for reporting this. Please try the latest dev build, It should be fixed. 
http://ci.citizensnpcs.co/job/HyperMerchant/40/

**Comment by mb243** [comment]
Getting this one now:

```
22:13:58] [Server thread/INFO]: [HyperMerchant] Enabling HyperMerchant v1.6.1-dev
[22:13:58] [Server thread/INFO]: [HyperMerchant] §e Citizens not found. NPC hypermerchants will be disabled.
[22:13:58] [Server thread/ERROR]: Error occurred while enabling HyperMerchant v1.6.1-dev (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at grokswell.util.MenuButtonData.loadMenuButtonData(MenuButtonData.java:78) ~[?:?]
	at grokswell.util.MenuButtonData.<init>(MenuButtonData.java:46) ~[?:?]
	at grokswell.hypermerchant.HyperMerchantPlugin.onEnable(HyperMerchantPlugin.java:413) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12-pre2.jar:git-Spigot-3c21190-3ecbb59]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by remremrem** [comment]
This is fixed finally. Thank you for your help!

**Comment by mb243** [comment]
Thank you for the fix! I'll deploy it and test shortly
