### ISSUE TITLE
Broken with 1.12

### ISSUE THREAD

**Issue by k-jiang** [remremrem/HyperMerchant#15]
Tested with:
HyperMerchant 1.6.1 build 40 (retrieve from Jenkins)
Spigot 1.12 build 1304

It seems that spigot 1.12 has changed some api. According to the thread you may need to reconfigure the build scripts and re-build it with the new version. [Link to the thread is here](https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12-pre6-released.240317/).

Exception while loading:
```
[17:53:08] [Server thread/INFO]: [HyperMerchant] Enabling HyperMerchant v1.6.1-dev
[17:53:08] [Server thread/ERROR]: Error occurred while enabling HyperMerchant v1.6.1-dev (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at grokswell.util.MenuButtonData.loadMenuButtonData(MenuButtonData.java:78) ~[?:?]
	at grokswell.util.MenuButtonData.<init>(MenuButtonData.java:46) ~[?:?]
	at grokswell.hypermerchant.HyperMerchantPlugin.onEnable(HyperMerchantPlugin.java:413) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

p.s. the plugin has no problem with Spigot 1.11.2

Thank you for your effort!

**Comment by k-jiang** [comment]
Just FYI: Some other plugins has the same issue as well (https://github.com/wargamer/SignShop/issues/40). They said it is due to `configuration.file.FileConfiguration.load` being removed.

**Comment by k-jiang** [comment]
I have fix it my self. Check your pull requests :)

**Comment by remremrem** [comment]
Thank you
